# Generated by Django 2.2.6 on 2019-10-28 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0002_auto_20191018_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriptionFix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('tax', models.FloatField()),
            ],
        ),
    ]
