# Generated by Django 2.2.6 on 2019-10-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0003_subscriptionfix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfix',
            name='end_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
