# Generated by Django 2.2.6 on 2019-10-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0005_auto_20191027_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionfix',
            name='user',
            field=models.TextField(unique=True),
        ),
    ]
