# Generated by Django 2.2.9 on 2020-01-15 22:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0009_auto_20191028_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 15, 14, 52, 6, 174365)),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='tax',
            field=models.FloatField(blank=True),
        ),
    ]
