# Generated by Django 2.2 on 2019-04-13 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='id',
            new_name='uuid',
        ),
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
