# Generated by Django 2.2 on 2019-04-15 23:08

import datetime
from django.db import migrations, models
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190412_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='md_content',
            field=markdownx.models.MarkdownxField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.date(2019, 4, 15)),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
