# Generated by Django 2.2 on 2019-04-15 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20190415_1638'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
