# Generated by Django 2.2 on 2019-04-16 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_company_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='company',
            field=models.ManyToManyField(to='home.company'),
        ),
    ]
