# Generated by Django 2.2.9 on 2020-01-15 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20190614_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='current',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
